# Generated by Django 2.1.2 on 2018-10-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=250)),
                ('can_view', models.CharField(max_length=350)),
                ('answer_counter', models.IntegerField()),
                ('form_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350)),
                ('question_number', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=32)),
                ('bans', models.IntegerField()),
                ('forms', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='ans',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.Form'),
        ),
        migrations.AddField(
            model_name='ans',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.Question'),
        ),
    ]
