# Generated by Django 2.1 on 2018-10-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
